### ISSUE TITLE
IE11 TypeError

### ISSUE THREAD

**Issue by infinity77** [PierreCapo/treeviz#54]
Hi Pierre,

it's always me, and I apologize as I know IE is not the best browser but in this situation I am forced to use it. After fixing the various (nodeData) => XX stuff, running Treeviz on IE11 I get this:

Unable to get property 'setProperty' of undefined or null reference

I even added the Array.prototype.find from here (https://gist.github.com/markhowellsmead/7fa5ad4a7d2eb6245cae13942da78b6a), but it still bombs out...

Do you happen to know what the problem is?

Thank you in advance.

Andrea.

**Comment by PierreCapo** [comment]
Hello Andrea,

I'm not an expert on that topic, and I'll need to investigate and spend some time on it. To give you some visibility, I'm a bit busy right now, I will be only able to investigate and find a solution next week only.

If this is urgent, here are my thoughts on the topic if you want to investigate furthermore :
- It's weird because the ts compiler output ES5 code which should be compatible with IE11 
 : https://github.com/PierreCapo/treeviz/blob/master/packages/treeviz/tsconfig.json#L4
- Seems like indeed the `setProperty` function can be found in https://github.com/PierreCapo/treeviz/blob/master/packages/treeviz/dist/index.js, so for whatever reason this code is not compatible with IE11 whereas the ts compiler outputs ES5 code.

Sorry for delaying the answer, I hope those explanations will help you.

Have a good day.

**Comment by infinity77** [comment]
Hi Pierre,

looking a bit on the debugging side, it appears that (at least part of) the reason is that the code uses "foreignObject" in two places (packages/treeviz/src/nodes/node-enter.ts and packages/treeviz/src/nodes/node-update.ts), and IE11 does not support foreignObject... do you think there is an alternative to that? I am sorry, I am really a noob when it comes to JavaScript, I have tried to look around on the web but I can't see any viable replacement.

Thank you.

Andrea.

**Comment by PierreCapo** [comment]
Hello Andrea, I have checked, and indeed, I reach the same conclusion as you. After adding es5 and es6 shim in the `index.html` file for ie 11 support:
- https://cdnjs.com/libraries/es5-shim
- https://cdnjs.com/libraries/es6-shim

I'm stuck with the `setProperty` and `foreignObject` issue. ForeignObject is not supported by IE and can't be polyfilled.
From what I have checked too, there is no straight forward solution, I'm sorry to say that, but seems like `treeviz` is not and won't be compatible for ie11.

What a nightmare that you have to support ie11 by the way, I feel bad for you.

Sorry not being able to help you on that one. Have a good day!

**Comment by infinity77** [comment]
Hi Pierre,

Thank you for your investigation on the matter. I have a backup plan anyway to avoid having to deal with IE, luckily enough there are Python libraries supporting the Chromium interface and I’m going to switch to those.
